carattere_sbagliato = '�'

corrections_ = {
    'Soggetto collettivo': 'Soggetto Collettivo',
    'soggetto collettivo': 'Soggetto Collettivo',
    'soggetto Collettivo': 'Soggetto Collettivo',
    'Costume e societa': 'Costume e società',
    'Politica e attivita istituzionali': 'Politica e attività istituzionali',
    'Pubblicita': 'Pubblicità',
    'Societa': 'Società',
    'Politica e attivit� istituzionali': 'Politica e attività istituzionali',
    'Costume e societ�': 'Costume e società',
    'Societ�': 'Società',
    'Bonaf�': 'Bonafè',
    'Miccich�': 'Miccichè',
    'Mul�': 'Mulè',
    'Santanch�': 'Santanchè',
    'Cirinn�': 'Cirinnà',
    'German�': 'Germanà',
    'Danz�': 'Danzì',
    'Urz�': 'Urzì',
    'Porr�': 'Porrà',
    'Cant�': 'Cantù',
    'Patan�': 'Patanè',
    'Calabr�': 'Calabrò',
    'Cass�': 'Cassì',
    'Macr�': 'Macrì',
    'Bertol�': 'Bertolè',
    'Schinin�': 'Schininà',
    'Carr�': 'Carrà',
    'Aric�': 'Aricò',
    'Verz�': 'Verzè',
    'Niccol� Maria': 'Niccolò Maria',
    'Nicol�': 'Nicolò',
    'Scutell�': 'Scutellà',
    'Zappal�': 'Zappalà',
    'Luc�': 'Lucà',
    'SKY TG24 SPECIALE - CITT� AL VOTO': 'SKY TG24 SPECIALE - CITTÀ AL VOTO',
    'Cal�': 'Calò',
    'Diventer� Bellissima': 'Diventerà Bellissima',
    'Union Vald�taine': 'Union Valdôtaine',
    "D'Inc�": "D'Incà",
    "NON � L'ARENA (TESTATA)": "NON È L'ARENA (TESTATA)",
    'Dess�': 'Dessì',
    'Dacc�': 'Daccò',
    'Samon�': 'Samonà',
    'Alver�': 'Alverà',
    'Desir�': 'Desirè',
    "LIVE NON � LA D'URSO": "LIVE NON È LA D'URSO",
    'Spirl�': 'Spirlì',
    "Noi con l�Italia-USEI-Cambiamo!-Alleanza di Centro": "Noi con l'Italia-USEI-Cambiamo!-Alleanza di Centro",
    'Azione - +Europa � Radicali Italiani': 'Azione - +Europa e Radicali Italiani',
    "L�Alternativa c��!": "L'Alternativa c'è!",
    "Noi con l'Italia�USEI�Rinascimento-AdC": "Noi con l'Italia, USEI, Rinascimento-AdC",
    'Cannistr�': 'Cannistrà',
    'Dur�': 'Durè',
    "PRESENTAZIONE 104� EDIZIONE GIRO D'ITALIA": "PRESENTAZIONE 104° EDIZIONE GIRO D'ITALIA",
    "Ver�": "Verì",
    "Carl� Campa": "Carlà Campa",
    "Niceta Pot�": "Niceta Potì",
    "Niccol�": "Niccolò",
    "Movimento Verde � Popolare": "Movimento Verde è Popolare",
    "TG1 E RAI QUIRINALE - CELEBRAZIONE DEL 77� ANNIVERSARIO DELLA LIBERAZIONE": "TG1 E RAI QUIRINALE - CELEBRAZIONE DEL 77° ANNIVERSARIO DELLA LIBERAZIONE",
    "LAlternativa c�-Lista del Popolo per la Costituzione": "LAlternativa c'è-Lista del Popolo per la Costituzione",
    "Gran�": "Granà",
    'LAlternativa c�!': "L'Alternativa c'è!",
    "Falcomat�": "Falcomatà",
    "Curr�": "Currò",
    "Schilir�": "Schilirò",
    "Jos�": "Josè",
    "Movimento 3V (Vaccini Vogliamo Verit�)": "Movimento 3V (Vaccini Vogliamo Verità)",
    "Chissal�": "Chissalè",
    "Petten�": "Pettenà",
    "Salm�": "Salmè",
    "STASERA C'� CATTELAN SU RAIDUE": "STASERA C'È CATTELAN SU RAIDUE",
    "Italia Viva - Italia C'�": "Italia Viva - Italia C'È",
    "L'Italia s'� desta": "L'Italia s'è desta",
    "3V Verit� e libert�": "3V Verità e libertà",
    "Al�": "Alì",
    "Lealt� Azione": "Lealtà Azione",
    "Giov�": "Giovì",
    "Pratic�": "Praticò",
    "Pellican�": "Pellicanò",
    "Muscar�": "Muscarà",
    "Facciamo Eco � Federazione dei Verdi": "Facciamo Eco - Federazione dei Verdi",
    "SANREMO 2021 - 71� FESTIVAL DELLA CANZONE ITALIANA": "SANREMO 2021 - 71° FESTIVAL DELLA CANZONE ITALIANA",
    "CAFF� EUROPA": "CAFFÈ EUROPA",
    "Pubblicit�": "Pubblicità",
    "Orr�": "Orrù",
    "SPECIALE CHE GIORNO �": "SPECIALE CHE GIORNO È",
    "Borr�": "Borrè",
    "Mont�": "Montà",
    "GAL Grandi autonomie e libert�": "GAL Grandi autonomie e libertà",
    "+ Europa �Centro Democratico": "+ Europa - Centro Democratico",
    "Movimento Nazionale per la Sovranit�": "Movimento Nazionale per la Sovranità",
    "Pi� Europa-Centro Democratico": "Più Europa-Centro Democratico",
    "NON � L'ARENA - IL MEGLIO DI (TESTATA)": "NON È L'ARENA - IL MEGLIO DI (TESTATA)",
    "C�cile": "Cècile",
    "Wagu�": "Waguè",
    "Democrazia � Libert� - La Margherita": "Democrazia è Libertà - La Margherita",
    "Zuccal�": "Zuccalà",
    "Giosu�": "Giosuè",
    "Pal�": "Palù",
    "ANTEPRIMA AGOR� ESTATE (TESTATA)": "ANTEPRIMA AGORÀ ESTATE (TESTATA)",
    "AGOR� ESTATE (TESTATA)": "AGORÀ ESTATE (TESTATA)",
    "Gioffr�": "Gioffrè",
    "Ciag�": "Ciagà",
    "And�": "Andò",
    "Chiric�": "Chiricò",
    "Scat�": "Scatà",
    "NON � L'ARENA (RETE)": "NON È L'ARENA (RETE)",
    "TG1 - LE CITT� D'EUROPA PER LA PACE": "TG1 - LE CITTÀ D'EUROPA PER LA PACE",
    "Andr�": "Andrè",
    "Comitato io Dico S�": "Comitato io Dico Sì",
    "Tot�": "Totò",
    "Carl�": "Carlà",
    "Mazz�": "Mazzà",
    "NON � L'ARENA SPECIALE (TESTATA)": "NON È L'ARENA SPECIALE (TESTATA)",
    "Verde � Popolare": "Verde è Popolare",
    "Raschill�": "Raschillà",
    "Sacc�": "Saccà",
    "Scarf�": "Scarfò",
    "Fig� Talamanca": "Figà Talamanca",
    "TGR - 68� RADUNO NAZIONALE BERSAGLIERI": "TGR - 68° RADUNO NAZIONALE BERSAGLIERI",
    "Mamm�": "Mammì",
    "Ballar�": "Ballarè",
    "Chitt�": "Chittò",
    "Id�": "Idà",
    "Maff�": "Maffè",
    "Span�": "Spanò",
    "TAGAD� LE STORIE (TESTATA)": "TAGADÀ LE STORIE (TESTATA)",
    'José': 'Josè',
    'Il s� delle Libert�': 'Il sì delle Libertà',
    'SANREMO 2020 - 70� FESTIVAL DELLA CANZONE ITALIANA': 'SANREMO 2020 - 70° FESTIVAL DELLA CANZONE ITALIANA',
    'Serran�': 'Serrano',
    'Verit�': 'Verità',
    'Benvegn�': 'Benvegnù',
    'Vall�e d\'Aoste Unie': 'Vallèe d\'Aoste Unie',
    'Marcian�': 'Marcianò',
    'S� Toscana a Sinistra': 'Sì Toscana a Sinistra',
    'Comitato Democratici per il S�': 'Comitato Democratici per il Sì',
    'Centro Democratico � Italiani in Europa': 'Centro Democratico - Italiani in Europa',
    'Cris�': 'Crisà',
    'AGOR� ESTATE SPECIALE': 'AGORÀ ESTATE SPECIALE',
    'ANTEPRIMA AGOR� ESTATE SPECIALE': 'ANTEPRIMA AGORÀ ESTATE SPECIALE',
    'Giuffr�': 'Giuffrè',
    'Giamp�': 'Giampà',
    'Scott�': 'Scottà',
    'TIKI TAKA IL CALCIO � IL NOSTRO GIOCO': 'TIKI TAKA IL CALCIO È IL NOSTRO GIOCO',
    'Chiamparino per il Piemonte del s�': 'Chiamparino per il Piemonte del sì',
    'Virz�': 'Virzì',
    'Pavor�': 'Pavorè',
    'Ven�': 'Venè',
    'TG2 - 64� REGATA DELLE ANTICHE REPUBBLICHE MARINARE': 'TG2 - 64° REGATA DELLE ANTICHE REPUBBLICHE MARINARE',
    'TGR - 66� RADUNO NAZIONALE BERSAGLIERI': 'TGR - 66° RADUNO NAZIONALE BERSAGLIERI',
    'C�': 'Cè',
    'Cu�': 'Cuè',
    'Schir�': 'Schirò',
    'Gull�': 'Gullì',
    'TG1 DIRETTA - 50� ANNIVERSARIO DELLA STRAGE DI PIAZZA FONTANA': 'TG1 DIRETTA - 50° ANNIVERSARIO DELLA STRAGE DI PIAZZA FONTANA',
    'PRESENTAZIONE 103� EDIZIONE GIRO D\'ITALIA': 'PRESENTAZIONE 103° EDIZIONE GIRO D\'ITALIA',
    'Facc�': 'Faccà',
    'Mar�': 'Marè',
    'PRES. NON � L\'ARENA (TESTATA)': 'PRES. NON È L\'ARENA (TESTATA)',
    'D�Angeli': 'D\'Angeli',
    'SKY TG24 SPECIALE - CITT� AL VOTO (I)': 'SKY TG24 SPECIALE - CITTÀ AL VOTO (I)',
    'D�Alberto': 'D\'Alberto',
    'TG1 E RAI QUIRINALE - CELEBRAZIONE DEL 73� ANNIVERSARIO DELLA LIBERAZIONE': 'TG1 E RAI QUIRINALE - CELEBRAZIONE DEL 73° ANNIVERSARIO DELLA LIBERAZIONE',
    'TGR - 24� RADUNO: ASSOCIAZIONE NAZIONALE CARABINIERI': 'TGR - 24° RADUNO: ASSOCIAZIONE NAZIONALE CARABINIERI',
    'TGR - 91� ADUNATA NAZIONALE ALPINI': 'TGR - 91° ADUNATA NAZIONALE ALPINI',
    'Pi� Europa': 'Più Europa',
    'Alternativa Popolare-Centristi per l�Europa - NCD': 'Alternativa Popolare-Centristi per l\'Europa - NCD',
    'Al� Listi': 'Alì Listì',
    'Civici e Innovatori-Energie per l�Italia': 'Civici e Innovatori-Energie per l\'Italia',
    'Noi con l�Italia-Scelta civica-MAIE': 'Noi con l\'Italia-Scelta civica-MAIE',
    'Grandi Autonomie e Libert� (G.A.L.)': 'Grandi Autonomie e Libertà (G.A.L.)',
    'L\'Italia � popolare': 'L\'Italia è popolare',
    'Deh�': 'Dehò',
    'Scamard�': 'Scamardì',
    'R�sch': 'Rösch',
    'LA CADUTA � STORIA DI UNA MORTE, DI UNA BANCA, DI UNA CITT�': 'LA CADUTA - STORIA DI UNA MORTE, DI UNA BANCA, DI UNA CITTÀ',
    'Cal� Lesina': 'Calà Lesina',
    'Ragione e Libert�': 'Ragione e Libertà',
    'Tradition et progr�s-Vall�e d\'Aoste': 'Tradition et progrès-Vallèe d\'Aoste',
    'Ingrill�': 'Ingrillì'
}